/// /////////////////////////////////////////////////////////////////////////////
//                             FUNCTION IMPORTS                               //
/// ////////////////////////////////////////////////////////////////////
import {
  adminAuthRegister,
  adminQuizCreate,
  adminQuizQuestionCreate,
  adminQuizGameStart,
  playerJoinGame,
  clear,
  adminQuizGameStateUpdate
} from './wrapperFunctions';

/// /////////////////////////////////////////////////////////////////////////////
//                                 CONSTANTS                                  //
/// /////////////////////////////////////////////////////////////////////////////
const HTTP_STATUS = {
  OK: 200,
  BAD_REQUEST: 400,
  INVALID_GAMEID: 400,
  INVALID_PLAYERNAME: 400,
  EMPTY_SESSION: 401,
  INVALID_SESSION: 401,
  UNAUTHORIZED: 403,
  INVALID_QUIZ: 403,
  FORBIDDEN: 403,
};

const VALID_AUTO_START_NUM = 5;

/// /////////////////////////////////////////////////////////////////////////////
//                             INITIALISATION                                 //
/// /////////////////////////////////////////////////////////////////////////////
const validFirstName = 'Hayden';
const validLastName = 'Smith';
const validEmail = 'hayden.smith@unsw.edu.au';
const validPassword = 'password6';
const name = 'Quiz 1';
const description = 'Valid Quiz Description';

let session: string;
let quizId: number;
let gameId: number;
let validPlayerName: string;

beforeEach(() => {
  clear();
  const registerResponse = adminAuthRegister(
    validEmail,
    validPassword,
    validFirstName,
    validLastName
  ) as { session: string };

  session = registerResponse.session;
  const createResponse = adminQuizCreate(session, name, description) as {
    quizId: number;
  };
  quizId = createResponse.quizId;
  adminQuizQuestionCreate(quizId, session, {
    question: 'What is the capital of France?',
    timeLimit: 30,
    points: 10,
    answerOptions: [
      { answer: 'Paris', correct: true },
      { answer: 'London', correct: false },
      { answer: 'Berlin', correct: false },
      { answer: 'Madrid', correct: false },
    ],
  }) as { questionId: number };
  const gameStartResponse = adminQuizGameStart(
    session,
    quizId,
    VALID_AUTO_START_NUM
  ) as { gameId: number };
  gameId = gameStartResponse.gameId;
  validPlayerName = 'Yuchao Jiang';
});

afterEach(() => {
  clear();
});

describe('Success Cases', () => {
  test('Correct Return Type', () => {
    expect(playerJoinGame(gameId, validPlayerName)).toStrictEqual({
      playerId: expect.any(Number),
    });
  });

  test('Accepts player even if name is an empty string', () => {
    const emptyName = '';
    expect(playerJoinGame(gameId, emptyName)).toStrictEqual({
      playerId: expect.any(Number),
    });
    // might need to check the status of the player -
    // like what his autogenerated username is if he was created;
  });

  test('Allows for multiple players to join the game', () => {
    const otherPlayer = 'Hayden Smith';
    expect(playerJoinGame(gameId, validPlayerName)).toStrictEqual({
      playerId: expect.any(Number),
    });
    expect(playerJoinGame(gameId, otherPlayer)).toStrictEqual({
      playerId: expect.any(Number),
    });
  });
});

describe('Error Cases', () => {
  test.each([
    { invalidName: 'SpecialCharsAbhi!' },
    { invalidName: 'ManySpecialChars!_~' },
  ])('Error testing for invalid name format inputted', ({ invalidName }) => {
    expect(playerJoinGame(gameId, invalidName)).toStrictEqual(
      HTTP_STATUS.INVALID_PLAYERNAME
    );
  });

  test('Name of user entered is not unique', () => {
    playerJoinGame(gameId, validPlayerName);
    const invalidNewPlayer = validPlayerName;
    expect(playerJoinGame(gameId, invalidNewPlayer)).toStrictEqual(
      HTTP_STATUS.INVALID_PLAYERNAME
    );
  });

  test('GameId does not refer to a valid game', () => {
    const invalidGameId = gameId + 112311212412412;
    expect(playerJoinGame(invalidGameId, validPlayerName)).toStrictEqual(
      HTTP_STATUS.INVALID_GAMEID
    );
  });

  test('Game is not in LOBBY state', () => {
    adminQuizGameStateUpdate(quizId, gameId, session, 'END');
    expect(playerJoinGame(gameId, validPlayerName)).toStrictEqual(
      HTTP_STATUS.BAD_REQUEST
    );
  });
});
